Fixed example query
The original query will throw:

```
...
clusto_query.exceptions.StringParseError: Found a . in system.memory; missing attr?
```